Sample Theory

In [1]:
import numpy as np

In [3]:
population= np.random.randint(0, 80, 10000)
population

array([41, 10, 53, ..., 46,  8, 67])

In [4]:
population[0:10] # Sample of 10

array([41, 10, 53, 37, 63, 56, 32,  4, 47, 46])

In [6]:
np.random.seed(10) # SAMPLİNG
Sample = np.random.choice(a= population, size=100)
Sample



array([16, 34, 34, 41, 52, 66, 55,  3, 71, 19, 42, 32, 14, 49, 32, 19, 58,
       35,  9, 75, 43, 38, 70,  0,  7, 41, 60, 18, 63, 70, 10, 54, 56, 74,
       37, 18, 30, 36, 33, 66, 19, 79,  1, 10,  7, 71, 26, 51, 21, 69, 43,
       72, 66, 73, 48, 68, 47, 37,  0, 29,  3, 78, 62, 12, 34, 42, 54, 79,
        0, 64, 61, 24, 14, 59, 14,  0, 70, 22, 36,  7, 30, 67, 13, 66, 66,
       62,  4,  8,  2, 37, 14, 43, 30, 38, 25, 53, 11, 75, 33, 75])

In [8]:
Sample.mean() # Sample Mean

39.04

In [9]:
population.mean() # Population Mean

39.6947

In [10]:
# Compare to population mean and sample mean

In [13]:
#Distrubation to Sample
Sample = np.random.choice(a= population, size=100)
Sample2 = np.random.choice(a= population, size=100)
Sample3 = np.random.choice(a= population, size=100)
Sample4 = np.random.choice(a= population, size=100)
Sample5 = np.random.choice(a= population, size=100)
Sample6 = np.random.choice(a= population, size=100)
Sample7 = np.random.choice(a= population, size=100)
Mean = (Sample.mean()+Sample2.mean()+Sample3.mean()+Sample4.mean()+Sample5.mean()+Sample6.mean()+Sample7.mean()) / 7
Mean


39.21857142857143